### ISSUE TITLE
Add non-ajax request support

### ISSUE THREAD

**Issue by TheNetsky** [TheNetsky/extensions-generic#11]
Some Madara sites do not use Ajax at all, add support for these sites.

**Comment by Ivanmatthew** [comment]
Are there any examples of website who don't use ajax?

**Comment by Ivanmatthew** [comment]
> Are there any examples of madara websites, who don't use Ajax?

@TheNetsky 
please don't leave me hanging sir 🙏

**Comment by TheNetsky** [comment]
Yes there are a couple, but this is not a priority. But a "nice to have". 
Examples:
https://manhwa18.cc
https://manga18fx.com/
