### ISSUE TITLE
Missing Cover 

### ISSUE THREAD

**Issue by mareign16** [TheNetsky/extensions-generic#18]
Paperback 0.7 - r46

MangaSee 2.2.0

all of my manga on mangasee extension (i try to add manga from mangasee extension but no cover)

on my library dont have cover but in Discover Tab have cover, i already try database repair but not working

![95C1AF93-8E25-4E49-8E61-C581834F5E24](https://user-images.githubusercontent.com/109650036/179914587-ab3bcb8e-d3df-4c0c-8521-e889c6b4db21.png)

**Comment by xOnlyFadi** [comment]
please follow the format
```
- App version (ex. 0.7 r34)
- Source(s) and their version(s) (ex. MadaraDex 2.0.3)
- Manga and chapters (ex. One Piece, Chapter 2)
- Detailed explanation of the issue
- And/or video/screenshot

**Comment by TheNetsky** [comment]
Migrate MangaSee > MangaSee, pick replace.
