### ISSUE TITLE
[BUG] Mangalek dosen't show the picture of the mang

### ISSUE THREAD

**Issue by Buenq** [TheNetsky/extensions-generic#20]
**Describe the bug**
Mangalek dosen't show the picture of the manga

**To Reproduce**

**Expected behavior**

**Screenshots/Video**

**App version**
- v0.7-r46

**Source WITH source version**
- Mangalek 2.2.1

**Additional context**

**Comment by Buenq** [comment]
what happened about this problem ?

**Comment by TheNetsky** [comment]
Nothing, still open.

**Comment by TheNetsky** [comment]
Fixed in latest update.
