### ISSUE TITLE
Madara - LeviatanScans (manga doesn't load)

### ISSUE THREAD

**Issue by Eyl-ien** [TheNetsky/extensions-generic#23]
**Describe the bug**
Clicking on ANY manga, in LeviatanScans, opens to a blank manga page. 

**To Reproduce**
1. Go to Leviathan Scans
2. Click on Any Manga
3. See error

**Expected behavior**
- Load manga title, chapters, thumbnails
- Read Now button/Bookmark/Tracker etc. 

**Screenshots/Video**

**- Source Manga Loads Properly:**
![image](https://user-images.githubusercontent.com/33476698/183268715-8101396d-7e55-47bf-9848-bf7d257f230e.png)

**- Problem When Opening Manga:**
![image](https://user-images.githubusercontent.com/33476698/183268666-2fae8e39-a55e-40c9-b169-f9a967182560.png)

**App version**
- v0.7-r46

**Source WITH source version**
- LeviatanScans 2.2.4

**Additional context**
No problems in other sources from Madara Extension

**Comment by TheNetsky** [comment]
Dupe #16

**Comment by Eyl-ien** [comment]
Okay thank you. If it’s okay, could you point me to a previous commit that solved this similar issue. 

I’m new to navigating github, but confident I can at least do this much myself to help.

**Comment by TheNetsky** [comment]
> Okay thank you. If it’s okay, could you point me to a previous commit that solved this similar issue.
> 
> I’m new to navigating github, but confident I can at least do this much myself to help.

It's just changing the path name to the current one they've set.

**Comment by Eyl-ien** [comment]
> > Okay thank you. If it’s okay, could you point me to a previous commit that solved this similar issue.
> 
> > 
> 
> > I’m new to navigating github, but confident I can at least do this much myself to help.
> 
> 
> 
> It's just changing the path name to the current one they've set.

Ah is it like the commit I just did?

**Comment by TheNetsky** [comment]
You didn't make any commit. I'll just fix it for one last time.
