### ISSUE TITLE
Manganato not working

### ISSUE THREAD

**Issue by Atem83** [TheNetsky/extensions-generic#26]
**Describe the bug**
Manganato source stopped to display manga since 15hours ago

**To Reproduce**
1. Go to Discover
2. Click on Manganato source tab
3. You will see a blank page in « last updates », « hot manga », « newest manga »

Alternative steps:
1. Go to Library
2. Click on All manga
3. You will see all manganato manga with a broken miniature and when you click on one manga, the chapter list is blank

**Expected behavior**
The discover and library favorites should display the database of manga of manganato with the chapters available but here it’s empty while the website manganato is available.
Maybe there are been modification to manganato website that has broken the source link ?

**Screenshots/Video**

![5E8CEFF4-53B3-4DD7-9CF8-3307C22DB2C9](https://user-images.githubusercontent.com/64048028/183743517-d04d3703-29aa-46dc-abcd-8c1012a502e7.png)

![2AEF87C2-4A47-4E98-A214-CA31C4A562F3](https://user-images.githubusercontent.com/64048028/183743611-baa9e324-62e1-4fa0-a3c4-f5df1aebea5f.png)

**App version**
- v0.7-r45

**Source WITH source version**
- Manganato nar1n 3.0.6

**Comment by TheNetsky** [comment]
Works fine for me, reinstall source/app.
