### ISSUE TITLE
LeviatanScans

### ISSUE THREAD

**Issue by endlessleep** [TheNetsky/extensions-generic#27]
Hello,
the source Leviatan Scans doesn’t show comic’s title, can you fix it ? 
![F6B64BEB-ACAF-4474-9825-0B7C3E73664C](https://user-images.githubusercontent.com/110991492/183927997-1d74f21a-1a10-49b3-abbb-5fac86ad6cba.png)
![211A6C26-1ECA-43EB-8835-5A6A5E2B1A70](https://user-images.githubusercontent.com/110991492/183928006-7dea9e8f-6c61-4dd2-9a54-04767dcb8a99.png)
here is examples… (sorry for my bad english)

**Comment by xOnlyFadi** [comment]
It got fixed in the recent push

**Comment by endlessleep** [comment]
Can you tell me how I update the Leviatan Scans ? please

**Comment by TheNetsky** [comment]
Should be automatically else Settings > repo > refresh/update

**Comment by endlessleep** [comment]
![4909F95A-917C-4906-8F5C-B39B95A32DFF](https://user-images.githubusercontent.com/110991492/184042943-53ffa93d-82c7-4181-b697-1992120ca173.png)
now it shows the title but the chapter have disappeared :(((((

**Comment by endlessleep** [comment]
it got fixed now, thanks lol

**Comment by xOnlyFadi** [comment]
can you close the issue
