### ISSUE TITLE
Hi Mangahub not working i tried doing cloudfre bypass and did not work as well

### ISSUE THREAD

**Issue by jokerxnc** [TheNetsky/extensions-generic#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**

**App version**
- v0.4-r69

**Source WITH source version**
- Readm 1.0.1

**Additional context**

**Comment by jokerxnc** [comment]
I have already delete and reinstall and is still not working any clues?

**Comment by TheNetsky** [comment]
It's broken.

**Comment by chlm1556** [comment]
Dunno if that can help.. here are some pictures of the text I get when I try to open a manga.
Looks like a bit when you added the cloudfare bypass a few weeks ago.. 
![DCD8376C-2BF6-42DA-94DF-329670D47FAC](https://user-images.githubusercontent.com/25506062/184121022-9101cedf-ee5e-40b9-88db-35f7432d1458.png)
![B68474CA-AE98-44B3-B2A6-6F01473902C8](https://user-images.githubusercontent.com/25506062/184121037-12c0519c-7080-4dd5-82af-280a05ca2aca.png)
![D3C3654C-53FD-47BC-BA33-98D876EF6FF6](https://user-images.githubusercontent.com/25506062/184121050-c3fab9c9-8383-440a-bced-13325fd7ea0e.png)

**Comment by SenorWhyMe** [comment]
rip went to mangahere for now but hope this gets fixed or paperback makes it easier to remove a source bookmarks for all manga at the moment i merged sources

**Comment by jokerxnc** [comment]
hopefully is fixable mangahub is the best :(

**Comment by chlm1556** [comment]
For me the cloudfare bypass works fine, I don’t know if it’s the same problem, or if it can help..

**Comment by TheNetsky** [comment]
Fixed in 2.0.7
