### ISSUE TITLE
Mangahub not working shortly after 2.0.7

### ISSUE THREAD

**Issue by chlm1556** [TheNetsky/extensions-generic#31]
Hi, 

Mangahub is not working for me I get errors when refreshing the manga page or directly in settings.

**Comment by TheNetsky** [comment]
Don't leak your email buddy!

**Comment by TheNetsky** [comment]
Also yes, Mangahub changed things again and broke it.

**Comment by TheNetsky** [comment]
Moved issue to correcty repo https://github.com/TheNetsky/netskys-extensions/issues
