### ISSUE TITLE
Mangakakalot not loading

### ISSUE THREAD

**Issue by Bcsotty** [TheNetsky/extensions-generic#34]
**Describe the bug**
None of the manga on mangakakalot shows up in app, but works fine in browser

**To Reproduce**
1. Go to discover
2. Click on Mangakakalot 

**Expected behavior**
The manga would load

**Screenshots/Video**

**App version**
- v0.7-r46

**Source WITH source version**
- Mangakakalot v3.0.6

**Additional context**
Was working fine ~6 hours ago. Hasn't worked since

**Comment by TheNetsky** [comment]
Add screenshots/video please.

**Comment by Bcsotty** [comment]
![image](https://user-images.githubusercontent.com/22244792/185004808-a7328e2e-c7e8-4841-9081-53b50429ca3a.png)

![image](https://user-images.githubusercontent.com/22244792/185004818-de72750c-946e-4fe7-8541-9fe066ca8244.png)

**Comment by TheNetsky** [comment]
Reinstall source/app
