### ISSUE TITLE
Mangakalot and manganato not working.

### ISSUE THREAD

**Issue by Acidix14** [TheNetsky/extensions-generic#35]
**Describe the bug**
Both sources doesn’t load anything, browser site works fine. Tried reinstalling sources and still nothing.

**To Reproduce**
1. After one chapter is done 
2. Cloud flare error pop up
3. Manga data disappears from library
4. Source stops loading stuff. Entire library doesn’t work 

**Expected behavior**
If I click on manga on broken source the data disappears. Doesn’t load up anything, tried reinstalling the source that is broken but it doesn’t work.

**Screenshots/Video**
![CEFAA885-5652-4E56-9F10-AB73D2217FA6](https://user-images.githubusercontent.com/111639295/185743866-80df2b2a-714a-4851-a152-a99fcc1d29f8.png)
![87410871-B087-4C1A-A8A2-CE4E53BE30EC](https://user-images.githubusercontent.com/111639295/185743867-519633dd-e76b-43ec-97b0-8bbfd741cc86.png)
![23C7063D-4783-448E-AC78-CE4C31F6A51C](https://user-images.githubusercontent.com/111639295/185743870-ba08b402-2de4-424a-9d26-a53727da4833.png)

**App version**
- v0.7~r45

**Source WITH source version**
- manganato/mangakalot nar1n 3.0.6

**Additional context**
Mangakalot hasn’t worked for months now. Manganato just stopped working. Only thing I noticed about it. Mangakalot only works when I’m connected to my works wifi. I will confirm this later today when I go back to work.

**Comment by TheNetsky** [comment]
Reinstall sources else reinstall app
