### ISSUE TITLE
"mangalek" does not work

### ISSUE THREAD

**Issue by fahad121264** [TheNetsky/extensions-generic#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**

**App version**
- v0.4-r69

**Source WITH source version**
- Readm 1.0.1

**Additional context**
![9b095766-b02b-4265-9b9b-467333462cb3](https://user-images.githubusercontent.com/53414999/190035045-4761fd81-7416-4116-acda-ddbceb1816e8.jpg)
![925b270d-1ed2-4003-af81-fa5763ad614b](https://user-images.githubusercontent.com/53414999/190035047-3c752439-6be2-4497-8ae1-5b091791072f.jpg)

**Comment by TheNetsky** [comment]
Invalid issue report, follow format
