### ISSUE TITLE
Problem with Resetscans

### ISSUE THREAD

**Issue by z33r4w** [TheNetsky/extensions-generic#41]
Hello. Actually my problem is quite simple when I try to read any comics it shows 
“JSError
Error: Unable to fetch numeric postld for this item!
Check if path is set correctly! - parsePostid@” 
![22DE3CF1-0004-4FB5-A9E4-EAEF22AD4BD2](https://user-images.githubusercontent.com/114528926/192628720-8bcfe953-a82e-4cc0-bb79-77620e51a62d.png)

**Comment by xOnlyFadi** [comment]
Please follow the format so we could know from which source is it 
```
- App version (ex. 0.7 r34)
- Source(s) and their version(s) (ex. MadaraDex 2.0.3)
- Manga and chapters (ex. One Piece, Chapter 2)
- Detailed explanation of the issue
- And/or video/screenshot

**Comment by TheNetsky** [comment]
Fixed

**Comment by z33r4w** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by z33r4w** [comment]
Thank you a lot

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
