### ISSUE TITLE
Mangakakalot Bad URL

### ISSUE THREAD

**Issue by xaelus** [TheNetsky/extensions-generic#42]
Hi, maybe two weeks ago this extension Mangabox started giving me errors.  I cannot load the Mangakakalot source, but I can load Mangabat and Manganato.  All other sources I use and extensions are working perfectly.  

I have uninstalled the source multiple times, I have uninstalled the repo as well.  Nothing seems to help, and oddly enough the URL in the screenshot works perfectly fine.  I have tried it using a VPN and without a VPN (Just to see if it mattered)  

The weird part is I get an error while loading Kakalot that reads nato, but I didnt even have Nato installed yet.  I have tried multiple combinations and I cannot seem to make heads or tails of it.  

- App version 0.7r47
- Source(s) and their version(s) - Mangakakalot (3.0.6) 
- Manga and chapters : All 
![IMG_0059](https://user-images.githubusercontent.com/114836988/193430858-8c779cc9-344d-4fda-b484-c9a8b504cd78.PNG)

**Comment by xaelus** [comment]
Here are a variety of screenshots of me attempting to refresh the sources, then navigating the sources in the main screen.  
![IMG_0061](https://user-images.githubusercontent.com/114836988/193430961-a5db43c1-0ce1-466b-9f32-168ff6f6bbb2.PNG)
![IMG_0062](https://user-images.githubusercontent.com/114836988/193430962-48e61825-0e15-47ed-9250-2ee4814824ec.PNG)
![IMG_0063](https://user-images.githubusercontent.com/114836988/193430963-8357cd51-b162-4191-8574-37de1a9f67fb.PNG)
![IMG_0064](https://user-images.githubusercontent.com/114836988/193430965-90a12988-5563-4edd-8ba6-2e14741501a3.PNG)
![IMG_0065](https://user-images.githubusercontent.com/114836988/193430966-38581f73-390b-49c7-bc6d-197cfa30b21e.PNG)
![IMG_0060](https://user-images.githubusercontent.com/114836988/193430967-80b0cd51-5b1d-4a82-828b-1eb97ad05f85.PNG)

**Comment by senorYME** [comment]
backup and delete the full app reinstall app and import backup back to paperback that's how it usually works when this issue arrives

**Comment by TheNetsky** [comment]
Try that first indeed @xaelus
