### ISSUE TITLE
MangaLife and MangaSee are Broken

### ISSUE THREAD

**Issue by Error404-NameNotFound** [TheNetsky/extensions-generic#43]
Explained in the title, but I’ll repeat it again. Manga Life and MangaSee stopped working for me today. I received an error when I tried to read manga from these sources, which can be seen below. I don’t actually know if it’s broken for anyone else, but it definitely is not working for me anymore. Hope this is fixed or it was really just me that had this problem.
![C6A23D3B-12EF-4F74-8770-90FAB7DD543C](https://user-images.githubusercontent.com/23133571/193437703-a4a1d946-2798-44f8-a593-64605a80aeb4.jpeg)

**Comment by TheNetsky** [comment]
Issue on your end, works fine for me. Try reinstalling the app.
