### ISSUE TITLE
MangaBat broken

### ISSUE THREAD

**Issue by waptik** [TheNetsky/extensions-generic#46]
**Describe the bug**
The MangaBox extension looks broken. No chapters can be found in its tab area inside the Discover page. Same with saved and downloaded chapters

**To Reproduce**
1. Go to Discover
2. Click on MangaBat tab
3. See that there are no chapters in latest updates and hot manga sections

**Expected behavior**
When you open the app and go to the tab belonging to MangaBat in Discover area, popular and updated chapters should be displayed. 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/1687551/201550388-bff65dfa-cbd2-4864-866a-51be39a89f77.png)
![image](https://user-images.githubusercontent.com/1687551/201550680-2fd67450-695e-42bc-9ecf-7049d8942f9b.png)
![image](https://user-images.githubusercontent.com/1687551/201550773-c5e8b3f8-58ff-464b-be9d-ffee43e924c4.png)

**App version**
- v0.7-r46

**Source WITH source version**
- MangaBat 3.0.7

**Additional context**

**Comment by Ivanmatthew** [comment]
Unable to reproduce the issue, are you sure it isn't your internet connection?

**Comment by trekuno** [comment]
Hello @Ivanmatthew @waptik having similar issues no issue with internet connection specific to mangakakalot*** see photos 
![unnamed (3)](https://user-images.githubusercontent.com/118643132/202878834-abe897ce-619c-4ed7-9528-7337ffd2c805.jpg)
![unnamed (2)](https://user-images.githubusercontent.com/118643132/202878836-472a7408-0c92-49a0-b4f7-57bee73bca43.jpg)
![unnamed (1)](https://user-images.githubusercontent.com/118643132/202878838-28bf5cc6-1ea9-4972-815f-65ad2effb263.jpg)
![unnamed](https://user-images.githubusercontent.com/118643132/202878840-44f7df58-1bcb-4735-9877-35a8df3e968b.jpg)

**Comment by trekuno** [comment]
I have all of them from that one source and as you can see it's not working tried removing source and reinstallation process and that was still unsuccessful.

**Comment by TheNetsky** [comment]
Reinstall app.

**Comment by trekuno** [comment]
(reinstall app) that worked, figured out how to restore it, thanks for the help!

**Comment by waptik** [comment]
> Reinstall app.

That fixed the issue but app started crashing when downloading chapters in bulk. It wasn't behaving so before I reinstalled the app.
