### ISSUE TITLE
Manga4life and Mangasee not loading thumbnails 

### ISSUE THREAD

**Issue by Kleankyrie2** [TheNetsky/extensions-generic#48]
**Describe the bug**
Mangas in Manga4life and Mangasee are not loading fast and thumbnails mostly aren't showing 
The mangas can't be downloaded properly too. 
**To Reproduce**
1. Go to discover
2. Click on manga4life
3. See error

**Expected behavior**
Manga and its thumbnails load fast.

**Screenshots/Video**

![IMG_6564](https://user-images.githubusercontent.com/120565949/208232011-0fa2bb29-2c64-4a55-a10e-4efd440c3a2e.jpg)
![IMG_6563](https://user-images.githubusercontent.com/120565949/208232016-7f9c16ca-9196-4259-b5bd-4d167a46aa5f.jpg)

**App version**
- v0.7-r46

**Source WITH source version**
- Manga4life v2.2.0

**Additional context**
It happens before.

**Comment by TheNetsky** [comment]
Fine for me, seems to be somerthing on your end,
