### ISSUE TITLE
Manganato

### ISSUE THREAD

**Issue by HiranoHisashi** [TheNetsky/extensions-generic#5]
![73AFB85D-F540-4370-AE97-3E1C7789D760](https://user-images.githubusercontent.com/105584639/168465505-2d17efb2-f7b1-4885-9d11-c3140c4ea5aa.png)
No manga from manganato even though the website is working.

**Comment by HiranoHisashi** [comment]
![C5485EFD-4835-4C1A-993A-8067CDEBAEDC](https://user-images.githubusercontent.com/105584639/168465484-dd0a81ea-bda6-42a4-af1f-bd5238d20eec.png)

**Comment by TheNetsky** [comment]
Please join the Discord server and provide actual useful information with your issue. "Doesn't work" with an image isn't anything useful.
