### ISSUE TITLE
[BUG] PianManga searches appearing like this?

### ISSUE THREAD

**Issue by Zefzed15** [TheNetsky/extensions-generic#50]
Everytime I try and search something up on PianManga and tap on a title it comes up blank. I tried reinstalling the app and the source and attempted again but it came up with this error code?

![627EA533-4056-4F9E-B323-DE19AE4B0D61](https://user-images.githubusercontent.com/9341185/216821776-436e7a53-31e4-45f4-ac27-9404976fd970.png)

**Comment by TheNetsky** [comment]
Source broken.

**Comment by Zefzed15** [comment]
what happens now
