### ISSUE TITLE
IsekeiScan all manga not working

### ISSUE THREAD

**Issue by Tremayah** [TheNetsky/extensions-generic#51]
**Describe the bug**
No images or updates loading, can only view title and previously loaded chapter numbers.

**To Reproduce**
1. Go to any IsekeiScan manga
2. Click on any IsekeiScan manga
3. See error

**Expected behavior**
To show any new chapters, and to load background image and thumbnail image.

**Screenshots/Video**
![FE48156C-D104-4864-B733-16ACAF569D22](https://user-images.githubusercontent.com/125309136/218559682-ce76570c-9865-4bbf-8f35-1029572bd4fc.png)

**App version**
- v0.7-r46

**Source WITH source version**
-IsekeiScan 2.2.5, by Netsky

**Additional context**
Been happening for about a week or two now. I have tried reinstalling and refreshing the source.

Logs:
[13-02.IsekaiScan.txt](https://github.com/TheNetsky/extensions-generic/files/10725799/13-02.IsekaiScan.txt)

**Comment by TheNetsky** [comment]
Website is dead

**Comment by Tremayah** [comment]
Any equivalent sources?

**Comment by TheNetsky** [comment]
That's for you to find out.
