### ISSUE TITLE
HentaiFox - Random pages cannot load

### ISSUE THREAD

**Issue by Chromagram** [TheNetsky/extensions-generic#54]
**Describe the bug**
For a number of manga titles from the HentaiFox source, random pages (particularly near the final few pages but sometimes other random places) will fail to load. On the new Paperback reader view, these pages just appear black. If you use the Legacy Viewer, it explicitly says "Failed to Load".

**To Reproduce**
1. Add the latest Bentai tracker.
2. Add the HentaiFox source.
3. Open random different manga to test this error. Not every single one does this, but many do.

**Expected behavior**
The source should load all pages of the manga without error. All failed loaded pages were also double checked on the HentaiFox website directly to ensure the pages are actually there. They appear on the site, but fail to load within the app only.

**Screenshots/Video**
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/44986450/226093863-35e4032c-8d81-43cf-87ac-4a09ccb498a3.png">

**App version**
- v0.7-r46

**Source WITH source version**
- HentaiFox 1.1.0

**Additional context**
It was mentioned earlier, but if you find a manga with pages that fail to load, generally I have found they have no problem loading on the website itself. It doesn't seem to be a matter of missing pages or broken images, more so that the source isn't loading some pages for whatever reason.

If even a page or two isn't loading at all, it also will fail to download a local copy.

**Comment by TheNetsky** [comment]
Going to need specific titles.

**Comment by Chromagram** [comment]
Sure thing, here's a few:

• Icha Love Nikushoku Girl - Lovesick Girls of Beast (Author: Hinahara Emi) [Halfway in, a large chunk of pages fail to load]
• Koibito Doushi + Motto Koibito Doushi 1&2 (Author: rico) [One of the last pages does not load]
• Ikenai! Ohimesama (Author: koume keito) [One of the last pages does not load]

More common is one of the last pages not loading, taking out the ending pages of a manga. Less common (but still only really happening with this source) is the first title, where literally a large chunk of pages will not load from any point, making the entire title unavailable to download.

**Comment by TheNetsky** [comment]
Already know the cause.

**Comment by Chromagram** [comment]
Something from my setup or something fixable from the source itself? It's good it's easily spottable at least.

**Comment by TheNetsky** [comment]
I gotta fix

**Comment by Chromagram** [comment]
Cheers, thank you.
