### ISSUE TITLE
ManhuaPlus chapter images not loading

### ISSUE THREAD

**Issue by dajrm89** [TheNetsky/extensions-generic#6]
App Version: v0.7-r38
Extensions: Madara
Source: ManhuaPlus 2.0.11
Manga / Chapter: Rebirth of the Urban Immortal Cultivator - Chapter 589

Hello! There seems to be a problem with the ManhuaPlus source, it gives an error when attempting to load pages. This issue persists across all mangas I’ve tried so far. Everything else seems fine.

Also, this doesn’t seem to be an issue with migrating from the original extensions to the new ones that were forked. I reinstalled Paperback and still experience the same, it’s been like this ever since I updated extensions a few days ago - other sources work fine.

![BDE3619B-DE46-464B-BD6B-B09C8CF56E02](https://user-images.githubusercontent.com/20587718/168529126-3c0b17bb-c512-4876-b517-011d71353d14.png)

Below is what was in the log file:

[ERROR] [2022-05-16T05:51:54.788Z] [ScrollBasedChapterRenderer:didAppear():1276] Processing image failed. Processor: WebPProcessor(identifier: "com.yeatse.WebPProcessor"). Processing item: data(14849 bytes). Kingfisher.KingfisherError.processorError(reason: Kingfisher.KingfisherError.ProcessorErrorReason.processingFailed(processor: KingfisherWebP.WebPProcessor(identifier: "com.yeatse.WebPProcessor"), item: Kingfisher.ImageProcessItem.data(14849 bytes)))

**Comment by TheNetsky** [comment]
Looked at it, sadly not something we can fix. Try reading from another source.
